services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    develop:
      watch:
        - action: sync
          path: .
          target: /app